package main

import (
	"bufio"
	"bytes"
	"fmt"
	"io"
	"os"
	"strconv"
	"strings"
)

/*
 * Complete the 'palindromeIndex' function below.
 *
 * The function is expected to return an INTEGER.
 * The function accepts STRING s as parameter.
 */

func isPalindrome(s string) bool {
	var reversedS bytes.Buffer

	for i := 0; i < len(s); i++ {
		reversedS.WriteString(s[len(s)-i-1 : len(s)-i])
	}

	return reversedS.String() == s
}

func palindromeIndex(s string) int32 {
	if isPalindrome(s) {
		return -1
	}

	for i := 0; i < len(s); i++ {
		// slow version
		/*if isPalindrome(s[:i] + s[i+1:]) {
			return int32(i)
		}*/
		// quick version
		//https://codingwithmanny.medium.com/how-to-solve-the-palindrome-index-code-challenge-1754f47dc8dd
		leftChar := s[i : i+1]
		rightChar := s[len(s)-1-i : len(s)-i]

		if leftChar != rightChar {
			if isPalindrome(s[:i] + s[i+1:]) {
				return int32(i)
			} else if isPalindrome(s[:len(s)-1-i] + s[len(s)-i:]) {
				return int32(len(s) - 1 - i)
			}
		}
	}

	return -1
}

func main() {
	// str := "lcpsklryvmcpjnbpbwllsrehfmxrkecwitrsglrexvtjmxypunbqfgxmuvgfajclfvenhyuhuorjosamibdnjdbeyhkbsombltouujdrbwcrrcgbflqpottpegrwvgajcrgwdlpgitydvhedtusippyvxsuvbvfenodqasajoyomgsqcpjlhbmdahyviuemkssdsldebesnnngpesdntrrvysuipywatpfoelthrowhfexlwdysvspwlkfblfdfultbwpiqhiymmyalcyeasvxggfitknygyvjxnspubqjppjbrlhugesmmxwjjlkrmgbnwvftyveolprfdcajiuywtvgfjrwwaakwyprxnxpypjgtlhfteetxbafkrejsfvrenlebjtccgjvrsdowiixlidxdiixpervseavnwypdinwdrlacvanhelkovkedcaxgctwysocddagwnjbkjorpceeyokeskcanvyornrustephpqtbhlrkrxlgjpavrcjpbyhosfimlavbtqcdevpwubfgshcmlofmpmektoyfquimnnqujgrgkymfjrsuixixmoihdhoveajsnanyihgsiuyrotnwtxwgmhprqhpvhyqwbgvmpefxagqqcgovenfsvummecklebihjhtylcalksfnytlfjqafoosssfhwhrfsybsldsyonecmantkhtrvkmqdsxdaqksrlnfpifevlikoxebfasdkguoyurbncvgpklfuslrhvevujwcjpiwxfnwafxojwwyhkheesxlpdjmmiqxxywwekvhpwvbtsbddihjdgwujijxqbxpcvojgkqyjoadjdgonobrwxmghwgaaepeagnhtggduihgmpvaewrbwhjggphiuymwibecjmhhvqnkhlklkfpiobquradoaplkssmdhvkfnapumdiwiahwcbtvbykdoxnkscpbycgmcyhqcrqksxjubfqdedisdwfwyuaawimchvsjojvjkhelmwqqcamhyrexpgbopnqwmmjdvfmgpqucpltrlibmagnrooheeaeqmntlugtkyopobliotkcvspojgxokxucnixyffssgkixlvicpuglpxaaeaoryjtottnbbitiseggaqlrmrecsgcyhsqicmwxhmaiwvsqdbyfskxffejxkmytfqckfbiopixnhsgkufpnqnuvrevfsuyynelthtkxfinmetyyboorflpyplgljimwmxstretyojnsdmtfeiyjtpkmdtamcmmokfkelhedqrvwfselddwauhmyboldbxtlghrrovufqtexmijrmgrjpgituuwvutjbbcvpaswqocqdmavyinlyutspqromnxpocngdhevvinaupvwbjiagcuwvolidlarqoytvfrtnhtkarhbepdkuxhqmubpjbiarjvponkexgoxbybfoeplcaeqwhjgltgddcttsgxsmosnntufxlscnxukferqxawddqwxwwqlmjcadwhdkbhxyelgjdajdwnipkgokwawieynejqokaplfbrqetcjqpuidbwnbamlenaiwqahtpubsptyjvidmdlrhjhkjtvpjvyhpbqlsmmlcgkneuqsydkimruvnqlapmjhpasioftsnehtaxnbbxlpsgniyckootvhwqplxmhlsoguovvsvjiorwarykiphhyexprweykwpssfoqaldkcuhemipvbwfcddtucxunvkiqrxhrlkdnimsuxksbjxdmexhgxevtrfmjfweqjjgrxbnvniywjflpfvxdauarcmehjiatrilpkboxmpxvujnahleiigcksgtdqvyifkbporpbhnyfamhhxlrhtwtndosukrfreihsaavknuppjwailtrfqnuuenrrfwjkitfitcujwmahkcrxvlfpybmgoexwdhhnbmwuotfohhxtlprjdyyealkrrioxqvltkkpcfwqogoirgablydpcqbtljilcgywqkourllircqlksmvtrmvjpruyagcifbarpwlbjtunkgbfuwanlvybotdqchahiccxypbkkvywecdyydonbnqpjtjlbjvjnajopkaagbamddoeidtjtlcfhlrjwpukphyhrbibcknhncoviifethjcubnrskekrgsmhdnmndvbgkyqtgupoetlihebuiomohbykonxsjbbuatqgogwubjdkphfxxupfvqrnepipslksfbbtkbqnkwxaggaebrjykbooswflirgpvjlikdvwatygaakdtvffytvrtdfevlutuicilxfntfvwhiadehidehwakceipbclkgvxebmbikxrtavaiggmndmbisjxuolhwhheltfthdmbdkdlqjahpoixitxfkkoitvmfsraauodaygmrqoyiejioegtqskyngnsyfubcledmlrfeieomowdufylyjlosbjrhhvlsaqgnklttrkiihmdpnroxffqgoknxgcrjuaygnvcfgkqoytgnlunqcexsqnrarjjnlkvygxgnkwemtkchhpblvyeoovojhawslstrsbhdanptatcjjfuhgawuvngeodyaxttswewwrotsjxeudafjaegxrncgseitxdmuhltbdpvonblqbqcdwjbpyexrihnimbftobwrrtgfwsyxldbjmcbniyisgvduyioomogekpjhkkhvoifdmirxiasqvymvjdmvrsackmluwsrldyrqijqsjljhkvfucrqvnryxgktdgnrjojcyssrefenrctmelgbbxcaeovjulbfcmhchdvlkaccdvphjxklxmneclnyyrebeodoraccceefavpktaxrpnvtymsaexbkmhyejcilgmrjljvfjtabhxuikoioolcdsbhcfrqmeivrtrafnahwxchjsrahdckwgtbllrxscvkvpmefmlennlyjdyqjecikvjxkeydiuphndlsrwafmlgvrinbmrjypuwcbvhktxrhddcwcefoqlnktdniuwjmthpvfwgywaicdnafrfvkqlunoixlhibcpqaupiwnihplupspwqaqdxeticiqkjucawapfyfngvyenttlmvertimdmuvaeqegnevsfeimahspdmdpkhifrwkhtghxyleoschxgpmiyfbetgvfogmidwpwfwweldsgicgqttcubdbxjwfaetjjqyjxygckmwqubylusprwsswfrehvxqiosrmraqempwjqvxnrnfohanorrvqppygiquaqnegdbptwnjqcqhlquakoxbencmvshxmuesahkvfyfxdxgoobqcqofwfikbbtcppgirotovuvtxuaolefnuvttbceffyhvqngiecyayvwwqwlcbsqxpmsqqyvvxftqvbcafbdfwaenwssbllbbxtuovsmvyhnukpwrsawsaeiawbdimemmbhbwcqsbaixmaxetxembiwdfyinlocbpjeomukpusqhvooposerdbwicfxqwbromvebtqtojkyfbpwridmnhlvltvcqyvfmslpmcjdovevwtvreygrirpwlmyclviaqvqfyaknwpjvlfpqhvkrobocpqfdopeflwmmwwavokubrkryjetaficuyjynyfunchabhbxvnuwhhqjqvdqdnvbnfcdhhbuliumrxmonhnxphhidmciaxjpdlvkuwhghfvadiotserklbuqnwanulgbxcnuyxegdagikwefcvppwnhmkhbishlsjbokysqcuxnfwrnyqfppsydeggobpawbbnlbicfdcskalxbcgsryrwdxdrcstbtvofywkecmaoolpqpvjjuchbckuggphanvimusqyhqqwegnveygbbpcgcamipulfsvrqokrxeiuiqkhwmpynfdvjdjuugiabetrufmsjwqtoddnpsmgaqcmvnhrtptvtopovcjfaabqgfevaredkhpgwwarounildyhgioilryrydpawwfhguqdrquinkqyoriwcwhnrghqlasjwxsfujiodewqopsfhbekblautklgmhrlhkqdwyrafpswfleppjaswcnrmyxbipmqcdvbfndkfwjlkodcafuwhiowkmxselljohktvqhdnqqahtdhyafhjtgtjeoppbbhimdgdkksebulvatubbemukggpuyhxaqhouprhamnekcakvwnyeavogdgeeqcehltecnoedeingkaekodooadxfmejdinmujtyxiddmoqvysajhexyeewjqduvliiiuchumnxccqxdjanrensktrvmuqigctpwxyrnmppogpurpilwxehuvehswscyotvospciftynjticetydyixwohsmaunqomgjcirkfraqlisqdtvedvdrfveissyjhftjqntvhwotfimkekohiuanqgvmbvvidrutgqrnnjjttxgxixgqsihlqdxsbudfmxbupvjdfuyytiwcgfvyndkhilakidpweqstmeytybsujsarxvqobdvjqxtydlwjdpdrvfowihstcsldqerrhpdypxaujwfookjkpxkahdtkvhnmlhgtyjuqjulvuqmlcvytvjugmqqkygympfgqqdhbbswxmljokikgthmiyfsanrmdyvtqbdtewscjeoaoykxtsmctuvvipkorgkikoeonwrydgysflsbgfecccaltlcltmtebxtqwnpbvqvdfoflvlqynqmheovybpffqbvpomqmdoqifxwclpdbipinegohwtmpvjhmvbabpsmvslaeddflspbywpgvktngfusdvueonskigkmjprviiwjhnpdajqioldtkyyyotjxbvkklfivpgfwvwaxjsgagjuqktpapbaqykcmrmihspeqngowyuyghtwrpprgsrwsfbfwoqhjgldvurutpucwocofrjlkdkfkolkfcrokfrjamewcbybqbrxublihvnrmberfvhqcbcengbrkdsdglbeommvkcqaeurjrycvdeaqnelxhebnperfsgdfjtfprxbjyghckjvanhxunblgffnxmqexnjpfhqqjwxlkjjkxsluhminsobsdtybjjsosjhcjhqtrcgpvrmfhvsckvupruqcglsbubegkwccyltwdhcmfwopumfnjxrpjmqgpwpbvrfvfasjjxxoungqcnglnadymvhdtwerrlnwljiwhhnewtubjdmwdrvqnevjbccunrscddykkprjjokvsysxqpqhvmsyquufpphssiggxxrkodghcygvqydomxodvlklbrgvdoebowlectlgttcmthcigsnceyphsvfxlkaajnelisteoyskgwsopjstikbdjjcwveyfteseymkplebubtlrfhnprrtdbxawcacxgwdflnuxrvuvsipapdqkumnxkouoqymwvpckgykaxfvsplsgrlsoxiniyiypkomieqsmsdnqkjlbxgjpsceqkrcmdbcnppxwgrjyuyrijfjjmsyhwfxjacvfgyuxqswwkhyigsqrycbnwcutkudkacpgdmetfcssltdtnvooxreuubqfxvrxxjebvlwdpqvdkyyawnougsrdvikuhcsflajjngmdylikmhkkvchewcjtmtotxhclhluutjatuieisquoscuqeemrablxipjsbepxpsrldxtvqomkshdxnprnsfndvwvydowthohmobjgrvsmgxmtpekimankxkjdbhykxgwpjgxddqqlqdhgktqwuehuqsxtaxebecsqkqtphkbaojibdbxxhhsyatsdtagaeyqoplfyviymtjnxknxrutsxpmdjojjskbhcmobkxcxtllrxaspwojwexapmlyhvcoxqgbcgfaasnuqppjpesmkspafbbmxgdxwlcyrhbubrpthfdylxmxqcaxfdmdjqehcgiwpkrscjplqslcraakecjjfvppovytehqtrkpvtfkkaxorxqfcsonxkdpcbovfwmaqwrpswadwxtrxkwcfnpdavvcwkxdhmfblwqevqjuqdoopnqubgbeewgchhhrtosgljkjcwesathshxnlgqplnvpxdwpanigbtskvpqoskxluvbiesxpgvhecgvctgkuadfxtyoolmagkdopvohflrlnxirsqcprfxrbwjpivrrjvibtxkyjclybvqvoslixlbcikrtimlritucrgedirclpuhenvnohoqsbkmjyaehtymofqtqkycatmekkrytirmjebvebanxbamjsgadfedcqkmbclxnfkwlouppugnwicgcjihqmnsexfhcshpaspohkgygmpfvrnabvhukupqsxbvsilvbdkkoqmweccatraxpjuafkraisvebkafnkrebebhidjdxwldmvxnbkfdvxaabmagcmbhpfixqohtltyyrymujtxftahumhervfymmjkdxtympxnhwccjvborbymqisifxjrnseqtxqgqqtxqxdatgqnjpaayvkevtxjpcbjctrskntdlwdhduummwplsarrwpbmtexwarrnflqskuaprwdetuqpwihvbkkupitramfhawaltcblygptdilbtsyudkpuuknvwufyrgmnkqykwrgdcrgvmfqpphnlrdjqxorswfgkviuucbxeuebhmrwcbmpupbnqsgjplrahcweeadjujmcvecbiqsdhuranxjfldiugfymgevdokimpkpabjdkewkruvwicfdinduvjtyxehnvtdvxocisyvmwtmfvtjehocdxxfyeombjryhhbrcdppakcfgvqngfrlgpsftitwtnwduawadnrfxtngretakloqdhxxprwlfvodwmfcawkasxgmcdnoqchulfucyrphofmnrrrtqcvjacxfhltypetcjoglivuwdhmwbfsthodktbpbplchpvlcmtnvskuvtivupoqwetjxwbbonewdckhpfwnxhkvburxkhoklktlkvoylsxqxjynqvdognkhjfitmwgakbnuycvkxubxgalwyqnfgaorfwotwuvhvjeuoahowjmfjaeisrpyufraciwbdsicfoytrhkoqwwcybnrvdqqkksnspowlabqqamihwaatwdsaqkvvdmhogwjxnijpjchkortlruhqxcrqoposdvjlusljcxbnaixpbsbunjonngedvuvbtfooadaebcsdmssplwlbiaoviuygsukmcbbfeelhieluaelldyplbgilejtwhejlimqosdwbjiwjokxulpgovqccbvbkdmvlapcuuywejvqbgqvtgeievkhyiijlvhyxwcsrdrwnnpqtgmpoqxsokcptlbhjjhjglcbowackpshxhwmbxhrikiexlohuvqejufxrfddwxmugjjjjqbubjyyvngslyyuwevqlyviwiffsoocgqwhcyjaorvdruaqavhnweyumechvrmcijlmkuncpjfhefagehwblvxycbgxusafforrlhtbsykahkglsfogbnfeqocnjfsqvkjhudlnfvnojwaecqkegqkyhomqtfkpstanyldghrusqwwsqiywblwibjburlnmhnajyfriyncpmbjdjkdkwauxlwufkiruxtgwaxiynmpbnbgxnjkklgkafgfrqxmptumttwvhjnkxorxcdippoartgwmxwbptwcnsclalynlnhjsmskejkvgtvstsvjoundnpoqeqepenayaujfewbkqwfmsevhylmncegiumxbaadcuohallmeksqfwopxbenfitnfgnjioonjdulpiyvvtnbsessfxhmidcqmqaufoiqtgfjqegmavquajnihuwqyahlsjiaatqtcxgscogemwymgnwqiujjwswpcgpecixehgwlufqjerwnfveqspcpiafmiwqkiqqrapfwvxhaqgpxcvovltltttgesyodsfusudrsbyvrflsiijgtdrqwnydjbrmvykqwniroinjncexmneirybqobuxeolaqvqnlyhchxlxapvogdwxebqsclrgddgtbwjoxqqgofgqwehdhhdliufmiyslebffaqvximgytmsrrcwyjbnrxuegtysxcafcrbbcpjdkwxeobbpkeffcaljtnerpgysaavcqfideghuhinunscrvnbrbhktolmomktfrciwkptuahrpdtiyjlqntdhkpvbegujaytwkjthlbycesmfeawrtcbgrwivffhgfbfrmyyybadhsrnyrmroosujqfhxlpesskkgllholmwgemfvyympskylphldyqvrdixovhejtdrxpxwqylgrvgfoprrokqgpbheaqkjlpclfckxbwfvsndjdwerjuayxjgxbqkmhoaoqlntispdivnlstfdohcorkpuccjlqjajwpdfkvlsrbemulrltwcnhrijtrwkdxvbpaibvttpwbermwfitivbaenwxkjekgfbgncekxvhyacmwhusprwsxkpywydkhknpapvkprupuwcrgynyskrtujstkxesiriijfvawqptptoxscwomqijabflbkejeototpqtiinaccywgxlsptepwkdxuhhbwepstimfqdfuhgsofgjubomayqyvaiwympsjxhqrmxmufhjkoshrjtrimsgncgmqvfcvpunctdwykilycsqlolwcedpilcchkggacvcvyawkkilmbfbpqatufjgroibyohyqgdofflrqtgfwlgpcijyovhgkphjhrkxxppfvbaoxgturdmvlywcufifwsqekdfksupqxrhvxetrhgpufnxaughtbxyndgxydqrbiaxherbnxrighigerqxsoyhuhftkxnmhpkqterjclskubryuiaoyyvvjdrtegglvseswxcckwmfbehvohkqiimrofmslugjomclkfnwebffhmcytopexcyohljuipfwcjloqymvcrbkeflaubgudfjnsskckryoemdumpqqhudnaopwpwtvcdlvxvxkqyyumfpbujrfgxuimlgdiabkgmigkitbiuxwaqxxarfgpaofnwkxalliatokdiongokgfkefelnumfcccmbcxmkxgcklmbysqlcvvieburxjyalcomgmytmixwtmytirfknesthnohwnjlrxxykauyiuvehwapogcfmvytlndlemwvkwwwwrvhotmytooiurpjprfbhimlulihjfeiacsowfpqvfbrytdoljrurfhpspwcwelwieohlexhlcbmxfblqvgidnxvfvyfcmeksssgaspnwrbuyegpcpaffyclwbqbpuliqgqsagiyaluysdquutbbsdorghuxegiupyppfbogmlhfrbdmueppjehplcnqkxnawgrchjkvuucovfeqltguypmmtcdeathwaybhimfghjwfqbvcvewwtjjnlntnjbkjdmslbxtkirpysleqpdnlnxybnspwwciaobnrbiclcrlufrowucikcjmrfeociyeaarrecwpeqdcwuqvquhbxsppxvhcfggfjbwndvdknhmmcdksxrwxlmoljxooewvnxuberhofobrsgcogwlfkavvjtkaxkvoirrmlydqpeklmoatnnyxnwuaqhcqrbhbuapgytwrajdnadhosimifhkxpnqhoyklydrawqryawmactoueegllqjdebnucagbdadcqxcsuotxlkupqbcfsniyqxwsyfvcgafyxhsuxoujbqcstgxotiolhngisdmbfrbfbtackvllonekteaqpqewekhyptbuocarxdtibgvrvdcshejwupvbaddqaenoiqiitdsuloohrqcavnysdxwebawdgmtoddyygrvrgkbycgbatcuxatcetbhcncqtfrsnjphqckreqsgluejxxncsqjwgnoauivisnrjpdbwvvfhsjsqiisdyfagsqioaeysrrekwhhsfmdxwvrhfmkgrmmlevcgcdywufhtmqprdsrcqjjxwvfqlteppgxukyrhebesrtkumeadqlepkjgvdlnvtlqgkkoqlsjdovabaagsmkiytruadkvyvogiywykringenjgqpafdieyayyflwhhlnrkmqugbkofyxlrplwswbuyctfnrowdeoqqfnygynnanbrdpoymrvntpujjjgnnuggctfkssauiboosdpfwlvqbqalbibqfjxjddtyyv"
	// fmt.Println(palindromeIndex(str))

	fmt.Println(palindromeIndex("a"))       // -1
	fmt.Println(palindromeIndex(""))        // -1
	fmt.Println(palindromeIndex("acbdbba")) // -1
	fmt.Println(palindromeIndex("aaab"))    // 3
	fmt.Println(palindromeIndex("acbba"))   // 1

}

func main2() {
	reader := bufio.NewReaderSize(os.Stdin, 16*1024*1024)

	qTemp, err := strconv.ParseInt(strings.TrimSpace(readLine(reader)), 10, 64)
	checkError(err)
	q := int32(qTemp)

	for qItr := 0; qItr < int(q); qItr++ {
		s := readLine(reader)

		result := palindromeIndex(s)

		fmt.Printf("%d\n", result)
	}
}

func readLine(reader *bufio.Reader) string {
	str, _, err := reader.ReadLine()
	if err == io.EOF {
		return ""
	}

	return strings.TrimRight(string(str), "\r\n")
}

func checkError(err error) {
	if err != nil {
		panic(err)
	}
}
